name: PR checks

on:
  pull_request:

jobs:
  format-lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff pytest

      - name: Format check
        run: ruff format --check

      - name: Lint check
        run: ruff check

      - name: Run tests
        run: pytest tests --runslow
